export const ROUTES = {
  AUTH: "/auth",
  MARKET: "/",
  LOGIN: "/login",
  REGISTER: "/register",
  DASHBOARD: "/dashboard",
  PROFILE: "/profile",
  NOT_FOUND: "*",
  SEARCH_PAGE: "/products",
  HELP_PAGE:'/help',
  PRODUCT_DETAILS_PAGE: "/product/:id",
  ADD_TO_CART: "/addtocart",
  CHECKOUT: "/checkout",
  PAYMENT_PAGE:"/paymentpage",
  SELLER_PAGE:"/seller",
} as const;
